diplom second part
muhammad-di/java-explore-with-me pull request #4
Opened 2023-12-04 18:43 UTC by muhammad-di

2023-12-10 18:39 UTC, muhammad-di commented
Привет, Евгений!
Я знаю что в проекте много недочетов, но я очень старался))
Это наверное самое тяжелое приложение которое я писал 🤯
Но должен признать это помогло мне выявить мои слабые стороны 😤
Уже наметил книги для чтения, чтобы закрыть эти пробелы)

2023-12-10 19:01 UTC, EugeneLenkevich requested changes
Привет, Мухаммад! Спасибо за PR.

Отличная работа! :)
В первую очередь хотелось бы привести в порядок форматы дат. С точки зрения красоты - это больше всего в глаза бросается

2023-12-10 19:01 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/controller/events/EventController.java
> +                                             @DateTimeFormat(pattern = DATE_TIME_FORMAT)
Давай попробуем настроить форматы даты и времени глобально, чтобы не приходилось вот так везде аннотациями это указывать :)

https://www.baeldung.com/spring-boot-formatting-json-dates

2023-12-10 20:45 UTC, muhammad-di commented on ewm-service/src/main/java/ru/practicum/mapper/ViewStatsMapper.java
> +    public static Collection<ViewStatsDto> toViewStatsDtoList(Object objectList) {
Меня и самого раздражает что у меня форматирование происходит на местах в контроллерах((
Я раньше уже пытался настроить spring boot
Но без успеха(
Мы даже обсуждали этот вопрос в пачке
Все равно не понятно почему приложение не подтягивает БИНЫ из config папки.
И потом уже от безисходности пришлось на местах расставлять DateTimeFormat(
Я для наглядности оставил в комите файл MainServiceConfig в папке config
Если убрать @DateTimeFormat в Контролерах, десериализация падает(

2023-12-10 20:45 UTC, muhammad-di commented on ewm-service/src/main/java/ru/practicum/controller/events/EventController.java
> +                                             @DateTimeFormat(pattern = DATE_TIME_FORMAT)
Меня и самого раздражает что у меня форматирование происходит на местах в контроллерах((
Я раньше уже пытался настроить spring boot
Но без успеха(
Мы даже обсуждали этот вопрос в пачке
Все равно не понятно почему приложение не подтягивает БИНЫ из config папки.
И потом уже от безисходности пришлось на местах расставлять DateTimeFormat(
Я для наглядности оставил в комите файл MainServiceConfig в папке config
Если убрать @DateTimeFormat в Контролерах, десериализация падает(

2023-12-11 05:51 UTC, EugeneLenkevich commented on ewm-service/src/main/java/ru/practicum/controller/events/EventController.java
> +                                             @DateTimeFormat(pattern = DATE_TIME_FORMAT)
Ну во первых, сама работа на самом деле норм, понятно что какие то моменты можно сделать  лучше и тд и тп, но, в целом, все на месте, а перфекционизм - это палка о двух концах :)

Что касается дат, можно дебагер воткнуть в метод кастомизации и проверить во первых вообще он отрабатывает или нет.
А так возможные варианты:
 - не тот бин конфигурируем, то есть у нас есть еще похожие бины, которые в реальности и используются
 - конфигурация вообще не стартует

Через тест у меня с ходу не стартануло приложение, надо подкрутить, я б глянул, может вечером получится

А так вот что можно посмотреть

https://stackoverflow.com/questions/28324352/how-to-customise-the-jackson-json-mapper-implicitly-used-by-spring-boot

В первую очередь проверил бы вот это 

![image](https://github.com/muhammad-di/java-explore-with-me/assets/109306643/25d422b9-1dbe-40f6-b7c6-2850300d0a93)

А еще, как кардинальная мера, можно попробовать вообще объявить свой objectMapper со своими настройками, главное не забыть @Primary поставить, чтобы не было конфликтов бинов

![image](https://github.com/muhammad-di/java-explore-with-me/assets/109306643/fc77f128-c4bf-47cc-b53a-19670a06d498)

PS а вообще с датами вечно лютый гимор, плюс у нас еще есть такая замечательная вещь как часовые пояса )

Аппрувчик поставлю, чтобы не задерживать работу, все таки это несколько вне курса, хотя лучше разобраться, потому что похожие проблемы довольно часто встречаются :)

2023-12-11 05:53 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-12-11 08:32 UTC, merged